database_url = "postgres://postgres:T8djzP72lg@staking-postgresql-ha-pgpool.staking.svc.cluster.local:5432/bridge"
on_chain_endpoint = "https://api.devnet.solana.com"
sqlx_max_connections = 10
sqlx_min_connections = 2
sqlx_connect_timeout = 8
sqlx_idle_timeout = 8
sqlx_max_lifetime = 8
sqlx_logging = false
polling_sqlx_logging_level = "info"
polling_sleep_secs = 10
polling_batch_transactions = 100
polling_batch_sleep_millis = 10
polling_daily_sleep_hms = "4:0:0"