database_url = " postgres://custom_bridge:custom_bridge@localhost:5432/custom_bridge"
solana_web_api_node = "http://localhost:8002"
gari_web_api_node = "https://eks-dev-gari.chingari.io/staking"
gari_notification_node = "https://sfurvsh9ri.execute-api.ap-south-1.amazonaws.com/v1"
x_staking_api_key = ""
bridge_account_address = "6Rcnb5rMh5EUi2UxSApEnCkeKujNGkY4uLEH2bDHKCC9"
sqlx_max_connections = 10
sqlx_min_connections = 2
sqlx_connect_timeout = 8
sqlx_idle_timeout = 8
sqlx_max_lifetime = 8
sqlx_logging = false
polling_sqlx_logging_level = "info"
polling_sleep_secs = 10
polling_batch_transactions = 100
polling_batch_sleep_millis = 10
polling_service_rust_log = "info"
polling_daily_sleep_hms = "4:0:0"
slack_webhook_url = "https://hooks.slack.com/services/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"
slack_channel_id = "C047LE9LELW"
slack_notification = false
instruction_metrics_row_limit = 10
esp_hosts = "b-1.test-cluster.uofz4n.c13.kafka.us-east-1.amazonaws.com:9092,b-2.test-cluster.uofz4n.c13.kafka.us-east-1.amazonaws.com:9092"
kafka_timeout = 5000
esp_topic = "stake_success_metrics"
enable_esp_kafka = false
clevertap_api_node = "https://api.clevertap.com/1"
clevertap_account_id = "656-85K-895Z"
clevertap_api_key = "daccbea8-87d3-476d-bbee-bb957df66693"
clevertap_notification = false
enable_datadog = false
datadog_host = "localhost"
datadog_port = "8125"
